### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by faizanahmad** [murongg/vue3-lazyload#27]
As soon as i start scrolling, there is an infinite loop of requests.
when I remove vue3-lazyload code it works fine. 
`v-lazy="{ src: productImage, loading: defaultImage, error: defaultImage }"`
what could be wrong?

![Screenshot 2022-05-30 at 12 27 23 AM](https://user-images.githubusercontent.com/139560/170888209-b61fd29c-d575-43a6-bfb0-572d6b0df2cd.png)

**Comment by murongg** [comment]
Please provide the problematic code to help me find the problem.

**Comment by murongg** [comment]
No reply

**Comment by Aanhane** [comment]
I would like to reopen this, because for me it's blocking as well. We have a setup where, if the `src` doesn't load (from a CDN), we would like to load the `error` image, which is the original unprocessed image. When the `errror`image doesn't load either, it will go into an infinite loop trying to load the images.

**Comment by murongg** [comment]
> I would like to reopen this, because for me it's blocking as well. We have a setup where, if the `src` doesn't load (from a CDN), we would like to load the `error` image, which is the original unprocessed image. When the `error` image doesn't load either, it will go into an infinite loop trying to load the images.

Can you provide a minirepo. I'll fix it as soon as possible

**Comment by murongg** [comment]
Fixed done, upgrade to latest version!
